### ISSUE TITLE
Simple Calculator

### ISSUE THREAD

**Issue by Ayushmaan2001** [photonbeam17/Calculator#4]
I can make a simple calculator that can add,subtract,multiply or divide according to user input. Can i work on this issue?? @photonbeam17

**Comment by photonbeam17** [comment]
Sure. Go ahead!

**Comment by photonbeam17** [comment]
I'm just using this project to learn how to use C++ though.

**Comment by photonbeam17** [comment]
Think next up is to add a modulo operation

**Comment by photonbeam17** [comment]
Also have to figure out how to loop the calculator's functions so I don't have to reboot each time

**Comment by photonbeam17** [comment]
I screwed up real bad; I had to revert all the changes sry
